//
// Created by Andri Yadi on 8/25/16.
//

#ifndef ESPECTRO_CONSTANTS_H_H
#define ESPECTRO_CONSTANTS_H_H

//Constants
#define ESPECTRO32_LED_PIN               	GPIO_NUM_15

#define ESPECTRO32_TOUCH_COUNT 				3

#define ESPECTRO32_RGBLED_PIN				GPIO_NUM_27
#define ESPECTRO32_RGBLED_COUNT				1   //Change this for another board type

#define ESPECTRO32_BUTTON_A_PIN              GPIO_NUM_0
#define ESPECTRO32_BUTTON_B_PIN              GPIO_NUM_4

#define ESPECTRO32_SDAPIN 					(GPIO_NUM_21)
#define ESPECTRO32_SCLPIN 					(GPIO_NUM_22)

#define ESPECTRO32_PHOTO_TR_ANALOG_CHANNEL  	ADC1_CHANNEL_0
#define ESPECTRO32_ALS_INT_PIN  				GPIO_NUM_36

#define ESPECTRO32_SDCARD_CSPIN				GPIO_NUM_33

/**
 * Contants for ESPectro32 v2
 */
#define ESPECTRO32_ACCEL_INT_PIN				GPIO_NUM_34
#define ESPECTRO32_BATT_ALERT_INT_PIN		GPIO_NUM_17
#define ESPECTRO32_TEMP_SENSOR_INT_PIN		GPIO_NUM_13
#define ESPECTRO32_LED_MATRIX_INT_PIN		GPIO_NUM_13
#define ESPECTRO32_ANALOG_MIC_IN_PIN			GPIO_NUM_35

//I2S
#define ESPECTRO32_I2S_TX_DATA_PIN			GPIO_NUM_32
#define ESPECTRO32_I2S_TX_BCLK_PIN			GPIO_NUM_26
#define ESPECTRO32_I2S_TX_WS_PIN				GPIO_NUM_25

#define ESPECTRO32_I2S_RX_DATA_PIN			GPIO_NUM_35
#define ESPECTRO32_I2S_RX_BCLK_PIN			GPIO_NUM_12
#define ESPECTRO32_I2S_RX_WS_PIN				GPIO_NUM_2

#endif //ESPECTRO_CONSTANTS_H_H
